# =============================================================================
# Settings page: Speaker mute, Mic mute, Auto answer toggles.
# =============================================================================
id: settings_mute_page
bg_color: 0x202020
on_swipe_left:
  - script.execute:
      id: ic_settings_navigate
      delta: 1
on_swipe_right:
  - script.execute:
      id: ic_settings_navigate
      delta: -1
on_swipe_down:
  - script.execute: ic_settings_close
widgets:
  - label:
      align: TOP_MID
      y: 28
      width: ${ic_settings_mid_width}
      text: "Speaker mute"
      text_color: 0xFFFFFF
      text_font: ${ic_settings_label_font}
      text_align: CENTER
  - switch:
      id: ui_speaker_mute_sw
      align: TOP_MID
      y: 52
      width: ${ic_settings_switch_width}
      height: ${ic_settings_switch_height}
      state:
        checked: !lambda 'return id(speaker_mute).state;'
      on_value:
        - lambda: |-
            if (x) id(speaker_mute).turn_on();
            else id(speaker_mute).turn_off();
  - label:
      align: TOP_MID
      y: 80
      width: ${ic_settings_wide_width}
      text: "Mic mute"
      text_color: 0xFFFFFF
      text_font: ${ic_settings_label_font}
      text_align: CENTER
  - switch:
      id: ui_mic_mute_sw
      align: TOP_MID
      y: 104
      width: ${ic_settings_switch_width}
      height: ${ic_settings_switch_height}
      state:
        checked: !lambda 'return id(mute).state;'
      on_value:
        - lambda: |-
            if (x) id(mute).turn_on();
            else id(mute).turn_off();
  - label:
      align: TOP_MID
      y: 132
      width: ${ic_settings_wide_width}
      text: "Auto answer"
      text_color: 0xFFFFFF
      text_font: ${ic_settings_label_font}
      text_align: CENTER
  - switch:
      id: ui_auto_answer_sw
      align: TOP_MID
      y: 156
      width: ${ic_settings_switch_width}
      height: ${ic_settings_switch_height}
      state:
        checked: !lambda 'return id(auto_answer_switch).state;'
      on_value:
        - lambda: |-
            if (x) id(auto_answer_switch).turn_on();
            else id(auto_answer_switch).turn_off();
  - label:
      align: TOP_MID
      y: 184
      width: ${ic_settings_wide_width}
      text: "DND"
      text_color: 0xFFFFFF
      text_font: ${ic_settings_label_font}
      text_align: CENTER
  - switch:
      id: ui_dnd_sw
      align: TOP_MID
      y: 208
      width: ${ic_settings_switch_width}
      height: ${ic_settings_switch_height}
      state:
        checked: !lambda 'return id(dnd_switch).state;'
      on_value:
        - lambda: |-
            if (x) id(dnd_switch).turn_on();
            else id(dnd_switch).turn_off();
