id: ic_ringing_out_page
bg_color: 0xFF9900
widgets:
  - label:
      align: TOP_MID
      y: 8%
      text: "${friendly_name}"
      text_color: 0xFFFFFF
      text_font: font_title
      text_align: CENTER
      width: ${ic_title_width}
      long_mode: SCROLL
  - label:
      align: TOP_MID
      y: 17%
      text: "CALLING"
      text_color: 0x000000
      text_font: font_state
      text_align: CENTER
  - label:
      id: ic_ringing_out_peer_label
      align: CENTER
      text: ""
      text_color: 0xFFFFFF
      text_font: font_title
      text_align: CENTER
      long_mode: SCROLL
      width: ${ic_peer_width}
  # Hangup below center
  - button:
      floating: true
      align: CENTER
      y: ${ic_btn_below_center}
      width: ${ic_btn_size}
      height: ${ic_btn_size}
      bg_opa: TRANSP
      shadow_opa: TRANSP
      widgets:
        - label:
            text: "\U000F03F5"
            align: CENTER
            text_color: 0xFF0000
            text_font: ic_icons
      on_short_click:
        - intercom_api.decline_call: intercom

# ========================================================================
# INTERCOM: IN CALL PAGE
# ========================================================================
