esphome:
  name: esphome-closet-doorway-probe
  friendly_name: BEsphome Closet doorway probe

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret encryption_key
ota:

  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset



esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor