esphome:
  name: esphome-workshop-north-wall-probe
  friendly_name: esphome-workshop-north-wall-probe

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0B1TfpNpiN9sguIkLjD0NgMQ8UGeSjqrO1q9fLv7C84="

ota:
  - platform: esphome
    password: "0a24549562430bafd23c4ff62857f257"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Workshop-North-Wall-Probe"
    password: "y26YaMn0mKuU"

captive_portal:
    