

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret encryption_key
ota:

  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${static_ip}
    gateway: 192.168.20.1
    subnet: 255.255.255.0

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: false
    interval: 320ms # default 320ms
    window:   300ms
bluetooth_proxy:
  active: false

# Enable logging
logger:

# Enable Home Assistant API
sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor