# =============================================================================
# Common speaker mute switch.
#
# Provides:
#   switch: speaker_mute
#
# Prerequisites:
#   - id `hw_speaker`    : speaker
#   - script id `update_status`
# =============================================================================

switch:
  - platform: template
    name: Speaker Mute
    id: speaker_mute
    icon: mdi:volume-off
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log:
          level: INFO
          tag: mute
          format: "Speaker mute ON"
      - speaker.mute_on: hw_speaker
      - script.execute: update_status
    on_turn_off:
      - logger.log:
          level: INFO
          tag: mute
          format: "Speaker mute OFF"
      - speaker.mute_off: hw_speaker
      - script.execute: update_status
