- platform: switch
  name: "Hotbox Lava Lamp"
  entity_id: switch.plug_hotbox_down_lavalamp
- platform: switch
  name: "Bedroom Lava Lamp"
  entity_id: switch.plug_bedroom_lavalamp
- platform: switch
  name: "Plasma Ball"
  entity_id: switch.plug_bedroom_plasmaball