esphome:
  name: bedroom-aux-2
  friendly_name: Bedroom Aux-2

# Replace this with your actual platform if you aren't using ESP32.
esp32:
  board: esp32dev

logger:

api:
  encryption:
    key: "HL5P1k1b4ZThWf8n41YNQeC8x6IkOMl/gO7lC+knwdw="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Bedroom Aux-2 Fallback Hotspot
    password: "WsiU6k0Gs3Pw"

captive_portal:
