substitutions:
  name: bermuda_kitchen_washer_probe
  friendly_name: bermuda kitchen washer probe
  static_ip: 192.168.20.153


packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml
