substitutions:
  name: bermuda_bathroom_sink_probe
  friendly_name: bermuda bathroom sink probe
  static_ip: 192.168.20.154

packages:
  - !include templates/SEEED-ESP32-C3/bluetooth_proxy_bermuda.yaml