substitutions:
  static_ip: 192.168.20.162
  name: bermuda_salon_corner_probe
  friendly_name: bermuda salon corner probe

packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml