substitutions:
  name: bermuda_hallway_desk_probe
  friendly_name: bermuda hallway desk probe
  static_ip: 192.168.20.152

packages:
  - !include templates/SEEED-ESP32-C3/bluetooth_proxy_bermuda.yaml