substitutions:
  name: bermuda_bedroom_bed_probe
  friendly_name: bermuda bedroom bed probe
  static_ip: 192.168.20.161

packages:
  - !include templates/SEEED-ESP32-C3/bluetooth_proxy_bermuda.yaml