substitutions:
  name: bermuda_closet_table_probe
  friendly_name: bermuda closet table probe
  static_ip: 192.168.20.155


packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml
