substitutions:
  static_ip: 192.168.20.140
  name: bermuda_hotbox_desk_probe
  friendly_name: bermuda hotbox desk probe

packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml

  