substitutions:
  static_ip: 192.168.20.159
  name: bermuda_hotbox_window_probe
  friendly_name: bermuda hotbox window probe

packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml