substitutions:
  static_ip: 192.168.20.142
  name: bermuda_workshop_wall_probe
  friendly_name: bermuda Workshop wall probe

packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml