substitutions:
  name: bermuda_closet_doorway_probe
  friendly_name: bermuda Closet doorway probe
  static_ip: 192.168.20.141


packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml