substitutions:
  name: bermuda_lounge_ganesha_probe
  friendly_name: bermuda Lounge Ganesha probe
  static_ip: 192.168.20.148


packages:
  - !include templates/ESP32-dev-boards/bluetooth_proxy_bermuda.yaml