substitutions:
  name: "hallway-assistant"
  friendly_name: hallway Assistant
  static_ip: 192.168.20.61
  network_subnet: 255.255.255.0
  gateway_ip: 192.168.20.1
  
packages:
  - !include templates/ESP32-S3-BOX-3/ESP32-s3-box-3_esphome_voice_assistant_with_audio_duplex_and_stop_word.yaml