substitutions:
  name: home-assistant-voice-09e4a7
  friendly_name: Home Assistant Voice Bedroom Assistant
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: tT4ILtL2iSwEAz8us3NrHVbQUVUKrpg7KHUsZGrIrXc=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
