esphome:
  name: mama-assistant
  friendly_name: MAma assistant

# Replace this with your actual platform if you aren't using ESP32.
esp32:
  board: esp32dev

logger:

api:
  encryption:
    key: "boN2+a/XmTzDl/GvrplRjk+P9kBgoXrvPdrpMA0Wr5I="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: MAma assistant Fallback Hotspot
    password: "tJbAal23NEIC"

captive_portal:
