substitutions:
  name: "salon-assistant"
  friendly_name: Salon Assistant
  static_ip: 192.168.20.63

packages:
  - !include templates/ESP32-S3-BOX-3/maxi_assistants_main_code_lvgl_border_touchscreen_audio_duplex_enabled.yaml
  

# remote_transmitter:
#   id: ir_tx
#   pin: 39
#   carrier_duty_percent: 50%
# remote_receiver:
#   id: ir_rx
#   pin:
#     number: 38
#     inverted: true
#     mode:
#       input: true
#       pullup: true
#   dump: all
#   tolerance: 25%
#   filter: 250us
#   idle: 10ms
#   buffer_size: 2048b
# infrared:
#   - platform: ir_rf_proxy
#     name: IR Proxy Transmitter
#     remote_transmitter_id: ir_tx
#   - platform: ir_rf_proxy
#     name: IR Proxy Receiver
#     receiver_frequency: 38kHz
#     remote_receiver_id: ir_rx
# switch:
#   - platform: gpio
#     id: enable_ir_rx
#     name: IR Receiver
#     pin:
#       number: GPIO44
#       inverted: true
#     restore_mode: ALWAYS_ON